docker run --rm --name $FEEDBACK_HOST \
  --network $DOCKER_NETWORK \
  -e LOGS_FOLDER_PATH=$LOGS_FOLDER_PATH \
  -v $LOGS_FOLDER_PATH:$LOGS_FOLDER_PATH \
  -p 8006:$FEEDBACK_PORT \
  $RAFIKI_IMAGE_FEEDBACK:$RAFIKI_VERSION